name: Create Archive
on: [push]
jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: pull latest and remove old file from repo
      run: |
        git config --global user.name "sailex428"
        git config --global user.email "elias.hahn@mail.de"
        git config pull.rebase false
        git pull
        rm -f release.zip
    - name: push changes to remote
      run: |
        git add -A
        git commit -m "new pack"
        git push --force
